apiVersion: v1
kind: {{ .Values.opdata.volume.kind }}
metadata:
  name: {{ .Values.opdata.volume.pvc.name }}
spec:
  accessModes:
    - {{ .Values.opdata.volume.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.opdata.volume.pvc.storage }}
  selector:
    matchLabels:
      name: {{ .Values.opdata.name }}
