apiVersion: v1
kind: {{ .Values.pgdata.volume.kind }}
metadata:
  name: {{ .Values.pgdata.volume.pvc.name }}
spec:
  accessModes:
    - {{ .Values.pgdata.volume.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pgdata.volume.pvc.storage }}
  selector:
    matchLabels:
      name: {{ .Values.pgdata.name }}
